import {FormEvent,useEffect,useMemo,useState} from "react";
type Role="Administrador"|"Dirección"|"Líder"|"Colaborador";
type User={id:string;name:string;email:string;password:string;role:Role;area:string;leader:string};
type Project={id:string;name:string;objective:string;areas:string[];base:number;target:number;unit:string;start:string;end:string;progress:number};
type Task={id:string;projectId:string;parentId?:string;title:string;owner:string;area:string;start:string;end:string;progress:number;status:string};
type Request={id:string;from:string;fromArea:string;to:string;toArea:string;task:string;status:"Pendiente"|"Aceptada"|"Rechazada";comments:string};
const U:User[]=[
 {id:"u1",name:"Jorge Mejía",email:"jorge@demo.com",password:"1234",role:"Administrador",area:"Inteligencia de Negocios",leader:"Armando Acosta"},
 {id:"u2",name:"Gabriel Sabogal",email:"gabriel@demo.com",password:"1234",role:"Dirección",area:"Dirección General",leader:"—"},
 {id:"u3",name:"Daniela Juárez",email:"daniela@demo.com",password:"1234",role:"Líder",area:"Ventas",leader:"Gabriel Sabogal"},
 {id:"u4",name:"Dante",email:"dante@demo.com",password:"1234",role:"Colaborador",area:"Ventas",leader:"Daniela Juárez"}];
const P:Project[]=[{id:"p1",name:"Crecimiento comercial FY26",objective:"Aumentar 30% las ventas respecto al FY anterior",areas:["Ventas","Marketing","Operaciones"],base:100,target:130,unit:"ventas",start:"2025-10-01",end:"2026-09-30",progress:60}];
const T:Task[]=[
 {id:"t1",projectId:"p1",title:"Contactar 50 prospectos diariamente",owner:"Dante",area:"Ventas",start:"2026-07-01",end:"2026-09-30",progress:82,status:"En tiempo"},
 {id:"t2",projectId:"p1",title:"Concretar 10 visitas por semana",owner:"Dante",area:"Ventas",start:"2026-07-15",end:"2026-09-30",progress:70,status:"En riesgo"},
 {id:"t3",projectId:"p1",title:"Campaña de captación B2B",owner:"Verónica",area:"Marketing",start:"2026-07-01",end:"2026-08-31",progress:52,status:"En riesgo"},
 {id:"t4",projectId:"p1",title:"Propuestas comerciales en menos de 48 h",owner:"Jorge Mejía",area:"Operaciones",start:"2026-07-01",end:"2026-09-15",progress:35,status:"Fuera de tiempo"}];
const R:Request[]=[{id:"r1",from:"Daniela Juárez",fromArea:"Ventas",to:"Jorge Mejía",toArea:"Inteligencia de Negocios",task:"Crear automatización para prospección comercial",status:"Pendiente",comments:"Apoyo requerido para aumentar el volumen de contactos diarios."}];
const nav:Record<Role,string[]>={Administrador:["Resumen","Proyectos","Usuarios","Aprobaciones"],Dirección:["Dashboard","Proyectos estratégicos","Cascada","Alertas"],Líder:["Mis objetivos","Mi equipo","Asignar actividades","Aprobaciones"],Colaborador:["Mi objetivo","Mis actividades","Mi plan","Solicitudes"]};
export default function App(){
 const [user,setUser]=useState<User|null>(null),[page,setPage]=useState(""),[projects,setProjects]=useState(P),[tasks,setTasks]=useState(T),[requests,setRequests]=useState(R),[modal,setModal]=useState(""),[selected,setSelected]=useState("p1"),[toast,setToast]=useState("");
 useEffect(()=>{const s=localStorage.getItem("oc-session"),p=localStorage.getItem("oc-projects"),t=localStorage.getItem("oc-tasks"),r=localStorage.getItem("oc-requests");if(s){const x=U.find(u=>u.id===s);if(x){setUser(x);setPage(nav[x.role][0])}}if(p)try{setProjects(JSON.parse(p))}catch{}if(t)try{setTasks(JSON.parse(t))}catch{}if(r)try{setRequests(JSON.parse(r))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("oc-projects",JSON.stringify(projects));localStorage.setItem("oc-tasks",JSON.stringify(tasks));localStorage.setItem("oc-requests",JSON.stringify(requests))},[projects,tasks,requests]);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};
 if(!user)return <Login enter={u=>{setUser(u);setPage(nav[u.role][0]);localStorage.setItem("oc-session",u.id)}}/>;
 const project=projects.find(p=>p.id===selected)||projects[0],pt=tasks.filter(t=>t.projectId===project.id);
 const logout=()=>{localStorage.removeItem("oc-session");setUser(null)};
 return <main className="v3"><aside><div className="brand"><b>IC</b><p>INTER-CON<span>OBJETIVOS EN CASCADA</span></p></div><div className="profile"><b>{user.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</b><p>{user.name}<span>{user.role} · {user.area}</span></p></div><nav>{nav[user.role].map((x,i)=><button key={x} className={page===x?"active":""} onClick={()=>setPage(x)}><i>{["▦","◎","☷","⚑"][i]}</i>{x}{x==="Aprobaciones"&&requests.some(r=>r.status==="Pendiente")&&<em>{requests.filter(r=>r.status==="Pendiente").length}</em>}</button>)}</nav><button className="logout" onClick={logout}>Cerrar sesión</button></aside>
 <section className="content"><header><div><small>FY 2026 · {page.toUpperCase()}</small><h1>{user.role==="Dirección"?"Dirección estratégica":user.role==="Líder"?"Gestión de mi equipo":user.role==="Colaborador"?"Mi contribución":"Administración del sistema"}</h1><p>Proyecto seleccionado: {project.name}</p></div><div><select value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>{user.role==="Dirección"&&<button className="primary" onClick={()=>setModal("smart")}>＋ Crear objetivo SMART</button>}{user.role==="Líder"&&<button className="primary" onClick={()=>setModal("assign")}>＋ Asignar actividad</button>}{user.role==="Colaborador"&&<button className="primary" onClick={()=>setModal("subtask")}>＋ Agregar actividad</button>}</div></header>
 {user.role==="Dirección"&&<Director project={project} tasks={pt} page={page}/>}
 {user.role==="Líder"&&<Leader project={project} tasks={pt} requests={requests} page={page} assign={()=>setModal("assign")} decide={(id,s)=>{setRequests(requests.map(r=>r.id===id?{...r,status:s}:r));notify("Solicitud "+s.toLowerCase())}}/>}
 {user.role==="Colaborador"&&<Worker project={project} tasks={tasks} page={page} update={(id,p)=>setTasks(tasks.map(t=>t.id===id?{...t,progress:p,status:p>=75?"En tiempo":p>=50?"En riesgo":"Fuera de tiempo"}:t))} request={()=>setModal("support")}/>}
 {user.role==="Administrador"&&<Admin projects={projects} tasks={tasks} requests={requests}/>}
 </section>
 {modal==="smart"&&<Smart close={()=>setModal("")} save={p=>{setProjects([...projects,p]);setSelected(p.id);setModal("");notify("Objetivo SMART creado")}}/>}
 {modal==="assign"&&<Assign project={project} close={()=>setModal("")} save={(t,cross)=>{if(cross){setRequests([...requests,{id:"r"+Date.now(),from:user.name,fromArea:user.area,to:t.owner,toArea:t.area,task:t.title,status:"Pendiente",comments:"Solicitud de apoyo interárea pendiente de validación."}]);notify("Solicitud enviada al líder del área")}else{setTasks([...tasks,t]);notify("Actividad asignada")}setModal("")}}/>}
 {modal==="subtask"&&<Subtask project={project} parent={tasks.find(t=>t.owner===user.name)} close={()=>setModal("")} save={t=>{setTasks([...tasks,t]);setModal("");notify("Actividad agregada a tu plan")}}/>}
 {modal==="support"&&<Support close={()=>setModal("")} save={r=>{setRequests([...requests,{...r,id:"r"+Date.now(),from:user.name,fromArea:user.area,status:"Pendiente"}]);setModal("");notify("Solicitud enviada a tu líder para visto bueno")}}/>}
 {toast&&<div className="toast">✓ {toast}</div>}</main>}
function Director({project,tasks,page}:{project:Project;tasks:Task[];page:string}){const areas=project.areas.map(a=>({a,items:tasks.filter(t=>t.area===a)})),avg=(xs:Task[])=>xs.length?Math.round(xs.reduce((s,x)=>s+x.progress,0)/xs.length):0,late=tasks.filter(t=>t.status==="Fuera de tiempo").length;return <><Hero p={project}/><section className="kpis"><K n={project.progress+"%"} l="Avance total" s="Contra meta estratégica"/><K n={String(project.areas.length)} l="Áreas responsables" s={project.areas.join(" · ")}/><K n={String(tasks.filter(t=>t.status==="En tiempo").length)} l="Actividades en tiempo" s={late+" fuera de tiempo"}/><K n={project.target+" "+project.unit} l="Meta del periodo" s={"Base: "+project.base}/></section><section className="dirGrid"><article className="card"><Title a={page} b="Avance y carga por área"/>{areas.map(x=><div className="areaRow" key={x.a}><b>{x.a}</b><div><i style={{width:avg(x.items)+"%"}}/></div><strong>{avg(x.items)}%</strong><span>{x.items.length} actividades</span></div>)}</article><article className="card"><Title a="Salud del proyecto" b="Información para tomar decisiones"/><div className="donut"><b>{project.progress}%</b><span>AVANCE</span></div><Metric a="Mayor carga" b={(areas.sort((x,y)=>y.items.length-x.items.length)[0]||{a:"—"}).a}/><Metric a="Área más rezagada" b={(areas.sort((x,y)=>avg(x.items)-avg(y.items))[0]||{a:"—"}).a}/><Metric a="Fuera de tiempo" b={String(late)}/></article></section><section className="card"><Title a="Actividades críticas" b="Prioridad por desviación"/>{tasks.sort((a,b)=>a.progress-b.progress).slice(0,4).map(t=><TaskRow t={t} key={t.id}/>)}</section></>}
function Leader({project,tasks,requests,page,assign,decide}:{project:Project;tasks:Task[];requests:Request[];page:string;assign:()=>void;decide:(id:string,s:"Aceptada"|"Rechazada")=>void}){return <><Hero p={project}/><section className="actionBanner"><div><b>Objetivo recibido de Dirección</b><span>Convierte este objetivo en actividades para tu equipo o solicita apoyo interárea.</span></div><button className="primary" onClick={assign}>Generar plan / asignar actividades</button></section>{page==="Aprobaciones"?<section className="card"><Title a="Solicitudes de otras áreas" b="Acepta, rechaza o comenta antes de asignar a tu colaborador"/>{requests.map(r=><div className="approval" key={r.id}><div><b>{r.from} solicita apoyo de {r.to}</b><span>{r.fromArea} → {r.toArea}</span><p>{r.task}</p><small>{r.comments}</small></div><em className={r.status}>{r.status}</em>{r.status==="Pendiente"&&<div><button onClick={()=>decide(r.id,"Rechazada")}>Rechazar</button><button className="primary" onClick={()=>decide(r.id,"Aceptada")}>Aceptar</button></div>}</div>)}</section>:<section className="leadGrid"><article className="card"><Title a={page} b="Personas y actividades bajo tu seguimiento"/>{["Dante","Mayra","Ana","Daniela"].map(n=>{const xs=tasks.filter(t=>t.owner===n),p=xs.length?Math.round(xs.reduce((s,x)=>s+x.progress,0)/xs.length):0;return <div className="person" key={n}><b>{n.slice(0,2).toUpperCase()}</b><p><strong>{n}</strong><span>{xs.length} actividades asignadas</span></p><div><i style={{width:p+"%"}}/></div><em>{p}%</em><button>Ver detalle</button></div>})}</article><article className="card"><Title a="Dependencias interárea" b="También visibles para el líder dueño del recurso"/>{requests.map(r=><div className="requestMini" key={r.id}><b>{r.toArea}</b><span>{r.task}</span><em>{r.status}</em></div>)}</article></section>}</>}
function Worker({project,tasks,page,update,request}:{project:Project;tasks:Task[];page:string;update:(id:string,p:number)=>void;request:()=>void}){const mine=tasks.filter(t=>t.owner==="Dante"),subs=tasks.filter(t=>t.parentId);return <><Hero p={project}/><section className="actionBanner"><div><b>Tu compromiso</b><span>Contactar 50 personas al día para generar 10 visitas semanales.</span></div><button className="primary" onClick={request}>Solicitar apoyo a otra área</button></section><section className="workerGrid"><article className="card"><Title a={page} b="Desglosa tu actividad en acciones necesarias"/>{mine.map(t=><div className="workerTask" key={t.id}><div><b>{t.title}</b><span>{t.start} — {t.end}</span></div><strong>{t.progress}%</strong><input type="range" value={t.progress} onChange={e=>update(t.id,+e.target.value)}/><em>{t.status}</em></div>)}<button className="addLocal" onClick={()=>document.querySelector<HTMLButtonElement>("header .primary")?.click()}>＋ Agregar actividad propia</button></article><article className="card"><Title a="Mi ruta de trabajo" b="Acciones para cumplir la actividad principal"/>{[["Conseguir cartera de clientes","Listo"],["Solicitar agente de prospección","En proceso"],["Automatizar contactos con apoyo de BI","Pendiente"]].map((x,i)=><div className="sub" key={x[0]}><b>{i+1}</b><p>{x[0]}<span>{x[1]}</span></p></div>)}</article></section></>}
function Admin({projects,tasks,requests}:{projects:Project[];tasks:Task[];requests:Request[]}){return <><section className="kpis"><K n={String(projects.length)} l="Proyectos" s="Configurados localmente"/><K n={String(tasks.length)} l="Actividades" s="En toda la cascada"/><K n={String(requests.length)} l="Solicitudes interárea" s="Flujo de aprobación"/><K n="4" l="Roles" s="Permisos simulados"/></section><section className="card"><Title a="Modelo funcional de la demo" b="Sin conexión a backend"/><div className="adminFlow">Dirección <i>→</i> Objetivo SMART <i>→</i> Líder <i>→</i> Colaborador <i>→</i> Subactividades <i>→</i> Avance</div></section></>}
function Hero({p}:{p:Project}){return <section className="hero"><div><span>PROYECTO · {p.id}</span><h2>{p.objective}</h2><p>{p.name} · Base {p.base} · Meta {p.target} {p.unit}</p><div className="chips">{p.areas.map(a=><b key={a}>{a}</b>)}</div></div><div className="ring"><b>{p.progress}%</b><span>AVANCE</span></div></section>}
function Smart({close,save}:{close:()=>void;save:(p:Project)=>void}){const [title,setTitle]=useState("Incrementar las ventas"),[base,setBase]=useState(100),[target,setTarget]=useState(130),[areas,setAreas]=useState(["Ventas"]),[ai,setAi]=useState(false);const toggle=(a:string)=>setAreas(areas.includes(a)?areas.filter(x=>x!==a):[...areas,a]);return <Modal close={close}><span className="ai">✦ ASISTENTE PARA OBJETIVOS SMART</span><h2>Construir objetivo estratégico</h2><div className="smartExplain"><b>¿Qué significa SMART?</b><span><i>S</i> Específico</span><span><i>M</i> Medible</span><span><i>A</i> Alcanzable</span><span><i>R</i> Relevante</span><span><i>T</i> Temporal</span></div><label>¿Qué quieres lograr?<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="fields"><label>Valor actual<input type="number" value={base} onChange={e=>setBase(+e.target.value)}/></label><label>Resultado esperado<input type="number" value={target} onChange={e=>setTarget(+e.target.value)}/></label></div><div className="fields"><label>Indicador<input defaultValue="Número de ventas cerradas"/></label><label>Fecha límite<input type="date" defaultValue="2026-09-30"/></label></div><label>Áreas responsables<div className="areaPick">{["Ventas","Marketing","Operaciones","Finanzas","Recursos Humanos","Inteligencia de Negocios"].map(a=><button type="button" className={areas.includes(a)?"on":""} onClick={()=>toggle(a)} key={a}>{a}</button>)}</div></label>{ai&&<div className="aiResult"><b>92/100 · Objetivo SMART</b><p>Propuesta de IA: “Incrementar de {base} a {target} las ventas cerradas antes del 30 de septiembre de 2026 mediante acciones coordinadas de {areas.join(", ")}.”</p><span>✓ Específico · ✓ Medible · ✓ Temporal</span></div>}<div className="actions"><button onClick={close}>Cancelar</button><button className="aiButton" onClick={()=>setAi(true)}>✦ Mejorar con IA</button><button className="primary" disabled={!ai} onClick={()=>save({id:"p"+Date.now(),name:title+" FY26",objective:"Incrementar de "+base+" a "+target+" las ventas cerradas antes del 30 de septiembre de 2026",areas,base,target,unit:"ventas",start:"2025-10-01",end:"2026-09-30",progress:0})}>Crear y asignar</button></div></Modal>}
function Assign({project,close,save}:{project:Project;close:()=>void;save:(t:Task,cross:boolean)=>void}){const [title,setTitle]=useState("Visitar 10 clientes por semana"),[area,setArea]=useState("Ventas"),[owner,setOwner]=useState("Dante");const cross=area!=="Ventas";return <Modal close={close}><span className="ai">PLAN DEL LÍDER</span><h2>Asignar actividad</h2><label>Objetivo relacionado<input value={project.objective} disabled/></label><label>Actividad<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="fields"><label>Área<select value={area} onChange={e=>{setArea(e.target.value);setOwner(e.target.value==="Inteligencia de Negocios"?"Jorge Mejía":"Dante")}}>{["Ventas","Marketing","Operaciones","Inteligencia de Negocios"].map(a=><option key={a}>{a}</option>)}</select></label><label>Responsable<select value={owner} onChange={e=>setOwner(e.target.value)}>{area==="Ventas"?["Dante","Mayra","Ana"].map(x=><option key={x}>{x}</option>):<option>{owner}</option>}</select></label></div><div className="fields"><label>Inicio<input type="date" defaultValue="2026-08-15"/></label><label>Fin<input type="date" defaultValue="2026-09-30"/></label></div>{cross&&<div className="warning">⚠ Esta persona pertenece a otra área. Se enviará una solicitud a su líder para aceptar, rechazar o comentar.</div>}<div className="actions"><button onClick={close}>Cancelar</button><button className="primary" onClick={()=>save({id:"t"+Date.now(),projectId:project.id,title,owner,area,start:"2026-08-15",end:"2026-09-30",progress:0,status:"Pendiente"},cross)}>{cross?"Enviar a validación":"Asignar"}</button></div></Modal>}
function Subtask({project,parent,close,save}:{project:Project;parent?:Task;close:()=>void;save:(t:Task)=>void}){const [title,setTitle]=useState("Conseguir cartera de clientes");return <Modal close={close}><span className="ai">MI PLAN DE ACCIÓN</span><h2>Agregar actividad propia</h2><p>Esta actividad contribuye a: <b>{parent?.title||project.objective}</b></p><label>Actividad<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="fields"><label>Inicio<input type="date" defaultValue="2026-08-15"/></label><label>Fin<input type="date" defaultValue="2026-08-22"/></label></div><div className="actions"><button onClick={close}>Cancelar</button><button className="primary" onClick={()=>save({id:"t"+Date.now(),projectId:project.id,parentId:parent?.id,title,owner:"Dante",area:"Ventas",start:"2026-08-15",end:"2026-08-22",progress:0,status:"Pendiente"})}>Agregar a mi plan</button></div></Modal>}
function Support({close,save}:{close:()=>void;save:(r:Omit<Request,"id"|"from"|"fromArea"|"status">)=>void}){const [task,setTask]=useState("Crear automatización para contactar prospectos");return <Modal close={close}><span className="ai">SOLICITUD DE APOYO</span><h2>Solicitar colaboración interárea</h2><label>Necesidad<input value={task} onChange={e=>setTask(e.target.value)}/></label><div className="fields"><label>Área requerida<select><option>Inteligencia de Negocios</option><option>Marketing</option><option>Operaciones</option></select></label><label>Persona sugerida<select><option>Jorge Mejía</option><option>Verónica</option></select></label></div><label>Justificación<textarea defaultValue="Necesito este apoyo para cumplir la actividad y alcanzar la meta asignada."/></label><div className="warning">La solicitud llegará primero a tu líder y posteriormente al líder del área requerida.</div><div className="actions"><button onClick={close}>Cancelar</button><button className="primary" onClick={()=>save({to:"Jorge Mejía",toArea:"Inteligencia de Negocios",task,comments:"Solicitud iniciada por colaborador; requiere visto bueno de ambos líderes."})}>Enviar solicitud</button></div></Modal>}
function Modal({children,close}:{children:React.ReactNode;close:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal wide"><button className="x" onClick={close}>×</button>{children}</div></div>}
function K({n,l,s}:{n:string;l:string;s:string}){return <article><b>{n}</b><p>{l}<span>{s}</span></p></article>}
function Title({a,b}:{a:string;b:string}){return <div className="cardTitle"><div><h3>{a}</h3><p>{b}</p></div></div>}
function Metric({a,b}:{a:string;b:string}){return <div className="metric"><span>{a}</span><b>{b}</b></div>}
function TaskRow({t}:{t:Task}){return <div className="taskRow"><b>{t.area.slice(0,2)}</b><p><strong>{t.title}</strong><span>{t.owner} · {t.end}</span></p><div><i style={{width:t.progress+"%"}}/></div><em>{t.progress}%</em><small>{t.status}</small></div>}
function Login({enter}:{enter:(u:User)=>void}){const [email,setEmail]=useState("gabriel@demo.com"),[pass,setPass]=useState("1234"),[error,setError]=useState("");const go=(e:FormEvent)=>{e.preventDefault();const u=U.find(x=>x.email===email&&x.password===pass);u?enter(u):setError("Datos incorrectos")};return <main className="loginPage"><section className="loginBrand"><div className="loginLogo">IC</div><span>INTER-CON</span><h1>La estrategia se convierte en trabajo visible</h1><p>Objetivos, responsables, aprobaciones y resultados conectados en una sola cascada.</p></section><section className="loginPanel"><form onSubmit={go}><span className="eyebrow">PORTAL DE OBJETIVOS</span><h2>Iniciar sesión</h2><label>Usuario<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" value={pass} onChange={e=>setPass(e.target.value)}/></label>{error&&<div className="loginError">{error}</div>}<button className="primary loginButton">Ingresar</button><div className="demoUsers">{U.map(u=><button type="button" key={u.id} onClick={()=>setEmail(u.email)}><span>{u.role}</span>{u.email}</button>)}<small>Contraseña: 1234</small></div></form></section></main>}
